"""create properties table

Revision ID: 494b15d982da
Revises:
Create Date: 2026-08-11 13:34:45.052810

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "494b15d982da"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "properties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("operation_type", sa.String(length=20), nullable=False),
        sa.Column("property_type", sa.String(length=50), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("zone", sa.String(length=100), nullable=True),
        sa.Column("bedrooms", sa.Integer(), nullable=True),
        sa.Column("bathrooms", sa.Integer(), nullable=True),
        sa.Column("covered_area", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("total_area", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="draft", nullable=False
        ),
        sa.Column("featured", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            status IN (\n                'draft',\n                'published',\n                'paused',\n                'reserved',\n                'rented',\n                'sold',\n                'unavailable'\n            )\n            ",
            name="ck_properties_status",
        ),
        sa.CheckConstraint(
            "operation_type IN ('sale', 'rent', 'temporary')",
            name="ck_properties_operation_type",
        ),
        sa.CheckConstraint(
            "bathrooms IS NULL OR bathrooms >= 0",
            name="ck_properties_bathrooms_non_negative",
        ),
        sa.CheckConstraint(
            "bedrooms IS NULL OR bedrooms >= 0",
            name="ck_properties_bedrooms_non_negative",
        ),
        sa.CheckConstraint(
            "covered_area IS NULL OR covered_area >= 0",
            name="ck_properties_covered_area_non_negative",
        ),
        sa.CheckConstraint(
            "price IS NULL OR price >= 0", name="ck_properties_price_non_negative"
        ),
        sa.CheckConstraint(
            "total_area IS NULL OR total_area >= 0",
            name="ck_properties_total_area_non_negative",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_properties_city"), "properties", ["city"], unique=False)
    op.create_index(op.f("ix_properties_code"), "properties", ["code"], unique=True)
    op.create_index(
        op.f("ix_properties_featured"), "properties", ["featured"], unique=False
    )
    op.create_index(
        op.f("ix_properties_operation_type"),
        "properties",
        ["operation_type"],
        unique=False,
    )
    op.create_index(op.f("ix_properties_price"), "properties", ["price"], unique=False)
    op.create_index(
        op.f("ix_properties_property_type"),
        "properties",
        ["property_type"],
        unique=False,
    )
    op.create_index(op.f("ix_properties_slug"), "properties", ["slug"], unique=True)
    op.create_index(
        op.f("ix_properties_status"), "properties", ["status"], unique=False
    )
    op.create_index(op.f("ix_properties_zone"), "properties", ["zone"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_properties_zone"), table_name="properties")
    op.drop_index(op.f("ix_properties_status"), table_name="properties")
    op.drop_index(op.f("ix_properties_slug"), table_name="properties")
    op.drop_index(op.f("ix_properties_property_type"), table_name="properties")
    op.drop_index(op.f("ix_properties_price"), table_name="properties")
    op.drop_index(op.f("ix_properties_operation_type"), table_name="properties")
    op.drop_index(op.f("ix_properties_featured"), table_name="properties")
    op.drop_index(op.f("ix_properties_code"), table_name="properties")
    op.drop_index(op.f("ix_properties_city"), table_name="properties")
    op.drop_table("properties")
    # ### end Alembic commands ###
