"""add property location fields

Revision ID: 72e21657338a
Revises: c7b62cd89c9e
Create Date: 2026-08-20 12:29:10.430125

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72e21657338a"
down_revision: str | Sequence[str] | None = "c7b62cd89c9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "propiedades", sa.Column("direccion", sa.String(length=200), nullable=True)
    )
    op.add_column(
        "propiedades",
        sa.Column("latitud", sa.Numeric(precision=9, scale=6), nullable=True),
    )
    op.add_column(
        "propiedades",
        sa.Column("longitud", sa.Numeric(precision=10, scale=6), nullable=True),
    )
    op.add_column(
        "propiedades",
        sa.Column(
            "mostrar_ubicacion_exacta",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        "ck_propiedades_coordenadas_completas",
        "propiedades",
        "\n            (latitud IS NULL AND longitud IS NULL)\n            OR\n            (latitud IS NOT NULL AND longitud IS NOT NULL)\n            ",
    )
    op.create_check_constraint(
        "ck_propiedades_latitud_valida",
        "propiedades",
        "latitud IS NULL OR (latitud >= -90 AND latitud <= 90)",
    )
    op.create_check_constraint(
        "ck_propiedades_longitud_valida",
        "propiedades",
        "longitud IS NULL OR (longitud >= -180 AND longitud <= 180)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_propiedades_longitud_valida", "propiedades", type_="check")
    op.drop_constraint("ck_propiedades_latitud_valida", "propiedades", type_="check")
    op.drop_constraint(
        "ck_propiedades_coordenadas_completas", "propiedades", type_="check"
    )
    op.drop_column("propiedades", "mostrar_ubicacion_exacta")
    op.drop_column("propiedades", "longitud")
    op.drop_column("propiedades", "latitud")
    op.drop_column("propiedades", "direccion")
    # ### end Alembic commands ###
